# Generated by Django 5.0.4 on 2024-04-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='carb',
            new_name='carbs',
        ),
    ]
